// 小蓝学词库 - 人教版3-5年级英语单词
// 共约344词，分20关，每关约17-20词

const WORDS = {
  // 三年级上册 (52词, 3关)
  "3a": [
    // Unit 1 学习用品 (9词)
    { en: "ruler", cn: "直尺" },
    { en: "pencil", cn: "铅笔" },
    { en: "eraser", cn: "橡皮擦" },
    { en: "crayon", cn: "蜡笔" },
    { en: "bag", cn: "包" },
    { en: "pen", cn: "钢笔" },
    { en: "pencil box", cn: "铅笔盒" },
    { en: "book", cn: "书" },
    // Unit 2 颜色 (8词)
    { en: "red", cn: "红色的" },
    { en: "green", cn: "绿色的" },
    { en: "yellow", cn: "黄色的" },
    { en: "blue", cn: "蓝色的" },
    { en: "black", cn: "黑色的" },
    { en: "brown", cn: "棕色的" },
    { en: "white", cn: "白色的" },
    { en: "orange", cn: "橙色的" },
    // Unit 3 身体部位 (11词)
    { en: "face", cn: "脸" },
    { en: "ear", cn: "耳朵" },
    { en: "eye", cn: "眼睛" },
    { en: "nose", cn: "鼻子" },
    { en: "mouth", cn: "嘴" },
    { en: "arm", cn: "胳膊" },
    { en: "hand", cn: "手" },
    { en: "head", cn: "头" },
    { en: "body", cn: "身体" },
    { en: "leg", cn: "腿" },
    { en: "foot", cn: "脚" },
    // Unit 4 动物 (11词)
    { en: "duck", cn: "鸭子" },
    { en: "pig", cn: "猪" },
    { en: "cat", cn: "猫" },
    { en: "bear", cn: "熊" },
    { en: "dog", cn: "狗" },
    { en: "elephant", cn: "大象" },
    { en: "monkey", cn: "猴子" },
    { en: "bird", cn: "鸟" },
    { en: "tiger", cn: "老虎" },
    { en: "panda", cn: "熊猫" },
    { en: "zoo", cn: "动物园" },
    // Unit 5 食物 (8词)
    { en: "bread", cn: "面包" },
    { en: "juice", cn: "果汁" },
    { en: "egg", cn: "蛋" },
    { en: "milk", cn: "牛奶" },
    { en: "water", cn: "水" },
    { en: "cake", cn: "蛋糕" },
    { en: "fish", cn: "鱼" },
    { en: "rice", cn: "米饭" },
    // Unit 6 数字 (10词)
    { en: "one", cn: "一" },
    { en: "two", cn: "二" },
    { en: "three", cn: "三" },
    { en: "four", cn: "四" },
    { en: "five", cn: "五" },
    { en: "six", cn: "六" },
    { en: "seven", cn: "七" },
    { en: "eight", cn: "八" },
    { en: "nine", cn: "九" },
    { en: "ten", cn: "十" }
  ],

  // 三年级下册 (52词, 3关)
  "3b": [
    // Unit 1 国家/人物 (15词)
    { en: "UK", cn: "英国" },
    { en: "USA", cn: "美国" },
    { en: "China", cn: "中国" },
    { en: "Canada", cn: "加拿大" },
    { en: "student", cn: "学生" },
    { en: "pupil", cn: "小学生" },
    { en: "teacher", cn: "教师" },
    { en: "she", cn: "她" },
    { en: "he", cn: "他" },
    { en: "boy", cn: "男孩" },
    { en: "girl", cn: "女孩" },
    { en: "new", cn: "新的" },
    { en: "friend", cn: "朋友" },
    { en: "today", cn: "今天" },
    // Unit 2 家庭 (13词)
    { en: "father", cn: "父亲" },
    { en: "dad", cn: "爸爸" },
    { en: "man", cn: "男人" },
    { en: "woman", cn: "女人" },
    { en: "mother", cn: "母亲" },
    { en: "mum", cn: "妈妈" },
    { en: "sister", cn: "姐/妹" },
    { en: "brother", cn: "兄/弟" },
    { en: "grandmother", cn: "（外）祖母" },
    { en: "grandma", cn: "奶奶/外婆" },
    { en: "grandfather", cn: "（外）祖父" },
    { en: "grandpa", cn: "爷爷/外公" },
    { en: "family", cn: "家" },
    // Unit 3 特征 (12词)
    { en: "thin", cn: "瘦的" },
    { en: "fat", cn: "胖的" },
    { en: "tall", cn: "高的" },
    { en: "short", cn: "矮的" },
    { en: "long", cn: "长的" },
    { en: "small", cn: "小的" },
    { en: "big", cn: "大的" },
    { en: "giraffe", cn: "长颈鹿" },
    { en: "so", cn: "这么" },
    { en: "children", cn: "儿童" },
    { en: "tail", cn: "尾巴" },
    // Unit 4 位置 (12词)
    { en: "on", cn: "在…上" },
    { en: "in", cn: "在…里" },
    { en: "under", cn: "在…下面" },
    { en: "chair", cn: "椅子" },
    { en: "desk", cn: "书桌" },
    { en: "cap", cn: "帽子" },
    { en: "ball", cn: "球" },
    { en: "car", cn: "小汽车" },
    { en: "boat", cn: "小船" },
    { en: "map", cn: "地图" },
    { en: "toy", cn: "玩具" },
    { en: "box", cn: "盒子" },
    // Unit 5 水果 (9词)
    { en: "pear", cn: "梨" },
    { en: "apple", cn: "苹果" },
    { en: "orange", cn: "橙子" },
    { en: "banana", cn: "香蕉" },
    { en: "watermelon", cn: "西瓜" },
    { en: "strawberry", cn: "草莓" },
    { en: "grape", cn: "葡萄" },
    { en: "buy", cn: "买" },
    { en: "fruit", cn: "水果" },
    // Unit 6 数字 (11词)
    { en: "eleven", cn: "十一" },
    { en: "twelve", cn: "十二" },
    { en: "thirteen", cn: "十三" },
    { en: "fourteen", cn: "十四" },
    { en: "fifteen", cn: "十五" },
    { en: "sixteen", cn: "十六" },
    { en: "seventeen", cn: "十七" },
    { en: "eighteen", cn: "十八" },
    { en: "nineteen", cn: "十九" },
    { en: "twenty", cn: "二十" },
    { en: "kite", cn: "风筝" },
    { en: "beautiful", cn: "美丽的" }
  ],

  // 四年级上册 (70词, 4关)
  "4a": [
    // Unit 1 教室 (11词)
    { en: "classroom", cn: "教室" },
    { en: "window", cn: "窗户" },
    { en: "blackboard", cn: "黑板" },
    { en: "light", cn: "电灯" },
    { en: "picture", cn: "图画" },
    { en: "door", cn: "门" },
    { en: "teacher's desk", cn: "讲台" },
    { en: "computer", cn: "电脑" },
    { en: "fan", cn: "风扇" },
    { en: "wall", cn: "墙" },
    { en: "floor", cn: "地板" },
    // Unit 2 文具 (9词)
    { en: "schoolbag", cn: "书包" },
    { en: "maths book", cn: "数学书" },
    { en: "English book", cn: "英语书" },
    { en: "Chinese book", cn: "语文书" },
    { en: "storybook", cn: "故事书" },
    { en: "notebook", cn: "笔记本" },
    { en: "candy", cn: "糖果" },
    { en: "toy", cn: "玩具" },
    { en: "key", cn: "钥匙" },
    // Unit 3 外貌 (12词)
    { en: "strong", cn: "强壮的" },
    { en: "friendly", cn: "友好的" },
    { en: "quiet", cn: "安静的" },
    { en: "hair", cn: "头发" },
    { en: "shoe", cn: "鞋" },
    { en: "glasses", cn: "眼镜" },
    { en: "his", cn: "他的" },
    { en: "or", cn: "或者" },
    { en: "right", cn: "正确的" },
    { en: "hat", cn: "帽子" },
    { en: "her", cn: "她的" },
    // Unit 4 房间 (14词)
    { en: "bedroom", cn: "卧室" },
    { en: "living room", cn: "起居室" },
    { en: "study", cn: "书房" },
    { en: "kitchen", cn: "厨房" },
    { en: "bathroom", cn: "浴室" },
    { en: "bed", cn: "床" },
    { en: "phone", cn: "电话" },
    { en: "table", cn: "桌子" },
    { en: "sofa", cn: "沙发" },
    { en: "fridge", cn: "冰箱" },
    // Unit 5 食物 (14词)
    { en: "beef", cn: "牛肉" },
    { en: "chicken", cn: "鸡肉" },
    { en: "noodles", cn: "面条" },
    { en: "soup", cn: "汤" },
    { en: "vegetable", cn: "蔬菜" },
    { en: "chopsticks", cn: "筷子" },
    { en: "bowl", cn: "碗" },
    { en: "fork", cn: "叉子" },
    { en: "knife", cn: "刀" },
    { en: "spoon", cn: "勺子" },
    { en: "dinner", cn: "晚餐" },
    // Unit 6 职业 (16词)
    { en: "parents", cn: "父母" },
    { en: "cousin", cn: "堂/表兄弟姊妹" },
    { en: "uncle", cn: "叔/伯/舅/姨父" },
    { en: "aunt", cn: "姑/姨/婶" },
    { en: "baby brother", cn: "婴儿弟弟" },
    { en: "doctor", cn: "医生" },
    { en: "cook", cn: "厨师" },
    { en: "driver", cn: "司机" },
    { en: "farmer", cn: "农民" },
    { en: "nurse", cn: "护士" },
    { en: "people", cn: "人们" },
    { en: "but", cn: "但是" },
    { en: "little", cn: "小的" },
    { en: "puppy", cn: "小狗" },
    { en: "football player", cn: "足球运动员" },
    { en: "job", cn: "工作" },
    { en: "basketball", cn: "篮球" }
  ],

  // 四年级下册 (50词, 3关)
  "4b": [
    // Unit 1 场所 (8词)
    { en: "first floor", cn: "一楼" },
    { en: "second floor", cn: "二楼" },
    { en: "teacher's office", cn: "教师办公室" },
    { en: "library", cn: "图书馆" },
    { en: "playground", cn: "操场" },
    { en: "computer room", cn: "计算机房" },
    { en: "art room", cn: "美术教室" },
    { en: "music room", cn: "音乐教室" },
    // Unit 2 餐食 (6词)
    { en: "breakfast", cn: "早餐" },
    { en: "English class", cn: "英语课" },
    { en: "lunch", cn: "午餐" },
    { en: "music class", cn: "音乐课" },
    { en: "PE class", cn: "体育课" },
    { en: "dinner", cn: "晚餐" },
    // Unit 3 天气 (9词)
    { en: "cold", cn: "寒冷的" },
    { en: "cool", cn: "凉爽的" },
    { en: "warm", cn: "温暖的" },
    { en: "hot", cn: "热的" },
    { en: "sunny", cn: "阳光充足的" },
    { en: "windy", cn: "有风的" },
    { en: "cloudy", cn: "多云的" },
    { en: "snowy", cn: "下雪的" },
    { en: "rainy", cn: "下雨的" },
    // Unit 4 蔬菜/动物 (8词)
    { en: "tomato", cn: "西红柿" },
    { en: "potato", cn: "土豆" },
    { en: "green beans", cn: "豆角" },
    { en: "carrot", cn: "胡萝卜" },
    { en: "horse", cn: "马" },
    { en: "cow", cn: "奶牛" },
    { en: "sheep", cn: "羊" },
    { en: "hen", cn: "母鸡" },
    // Unit 5 衣物 (12词)
    { en: "clothes", cn: "衣服" },
    { en: "pants", cn: "裤子" },
    { en: "hat", cn: "帽子" },
    { en: "dress", cn: "连衣裙" },
    { en: "skirt", cn: "裙子" },
    { en: "coat", cn: "外衣" },
    { en: "sweater", cn: "毛衣" },
    { en: "sock", cn: "袜子" },
    { en: "shorts", cn: "短裤" },
    { en: "jacket", cn: "夹克" },
    { en: "shirt", cn: "衬衫" },
    // Unit 6 配饰 (8词)
    { en: "glove", cn: "手套" },
    { en: "scarf", cn: "围巾" },
    { en: "umbrella", cn: "雨伞" },
    { en: "sunglasses", cn: "太阳镜" },
    { en: "pretty", cn: "漂亮的" },
    { en: "expensive", cn: "昂贵的" },
    { en: "cheap", cn: "便宜的" },
    { en: "nice", cn: "好的" }
  ],

  // 五年级上册 (60词, 3关)
  "5a": [
    // Unit 1 特征 (10词)
    { en: "old", cn: "年老的" },
    { en: "young", cn: "年轻的" },
    { en: "funny", cn: "滑稽可笑的" },
    { en: "kind", cn: "和蔼的" },
    { en: "strict", cn: "严格的" },
    { en: "polite", cn: "有礼貌的" },
    { en: "hard-working", cn: "努力工作的" },
    { en: "helpful", cn: "有帮助的" },
    { en: "clever", cn: "聪明的" },
    { en: "shy", cn: "害羞的" },
    // Unit 2 星期 (14词)
    { en: "Monday", cn: "星期一" },
    { en: "Tuesday", cn: "星期二" },
    { en: "Wednesday", cn: "星期三" },
    { en: "Thursday", cn: "星期四" },
    { en: "Friday", cn: "星期五" },
    { en: "Saturday", cn: "星期六" },
    { en: "Sunday", cn: "星期天" },
    { en: "weekend", cn: "周末" },
    { en: "wash", cn: "洗" },
    { en: "watch", cn: "看" },
    { en: "do", cn: "做" },
    { en: "homework", cn: "作业" },
    { en: "read", cn: "读" },
    { en: "play", cn: "玩" },
    // Unit 3 食物 (10词)
    { en: "sandwich", cn: "三明治" },
    { en: "salad", cn: "沙拉" },
    { en: "hamburger", cn: "汉堡包" },
    { en: "ice cream", cn: "冰淇淋" },
    { en: "tea", cn: "茶" },
    { en: "fresh", cn: "新鲜的" },
    { en: "healthy", cn: "健康的" },
    { en: "delicious", cn: "美味的" },
    { en: "hot", cn: "辣的" },
    { en: "sweet", cn: "甜的" },
    // Unit 4 活动 (16词)
    { en: "sing", cn: "唱" },
    { en: "song", cn: "歌曲" },
    { en: "dance", cn: "跳舞" },
    { en: "draw", cn: "画" },
    { en: "cook", cn: "烹调" },
    { en: "swim", cn: "游泳" },
    { en: "play basketball", cn: "打篮球" },
    { en: "play ping-pong", cn: "打乒乓球" },
    { en: "speak English", cn: "说英语" },
    { en: "play the pipa", cn: "弹琵琶" },
    { en: "Kung fu", cn: "功夫" },
    { en: "do kung fu", cn: "练武术" },
    { en: "draw cartoons", cn: "画漫画" },
    { en: "read books", cn: "看书" },
    // Unit 5 物品 (12词)
    { en: "clock", cn: "时钟" },
    { en: "plant", cn: "植物" },
    { en: "bottle", cn: "瓶子" },
    { en: "water bottle", cn: "水瓶" },
    { en: "bike", cn: "自行车" },
    { en: "photo", cn: "照片" },
    { en: "front", cn: "正面" },
    { en: "in front of", cn: "在…前面" },
    { en: "between", cn: "在…之间" },
    { en: "above", cn: "在…上面" },
    { en: "beside", cn: "在…旁边" },
    { en: "behind", cn: "在…后面" },
    // Unit 6 地点 (14词)
    { en: "forest", cn: "森林" },
    { en: "river", cn: "河流" },
    { en: "lake", cn: "湖泊" },
    { en: "mountain", cn: "高山" },
    { en: "hill", cn: "小山" },
    { en: "tree", cn: "树" },
    { en: "bridge", cn: "桥" },
    { en: "building", cn: "建筑物" },
    { en: "village", cn: "乡村" },
    { en: "house", cn: "房子" }
  ],

  // 五年级下册 (60词, 4关)
  "5b": [
    // Unit 1 活动 (14词)
    { en: "eat breakfast", cn: "吃早饭" },
    { en: "have class", cn: "上课" },
    { en: "play sports", cn: "进行体育运动" },
    { en: "exercise", cn: "活动" },
    { en: "do morning exercises", cn: "早锻炼" },
    { en: "eat dinner", cn: "吃晚饭" },
    { en: "clean my room", cn: "打扫房间" },
    { en: "go for a walk", cn: "散步" },
    { en: "go shopping", cn: "购物" },
    { en: "take", cn: "上（课）" },
    { en: "dancing", cn: "跳舞" },
    { en: "take a dancing class", cn: "上舞蹈课" },
    // Unit 2 季节 (12词)
    { en: "spring", cn: "春天" },
    { en: "summer", cn: "夏天" },
    { en: "autumn", cn: "秋天" },
    { en: "winter", cn: "冬天" },
    { en: "season", cn: "季节" },
    { en: "picnic", cn: "野餐" },
    { en: "go on a picnic", cn: "去野餐" },
    { en: "pick", cn: "摘" },
    { en: "pick apples", cn: "摘苹果" },
    { en: "snowman", cn: "雪人" },
    { en: "make a snowman", cn: "堆雪人" },
    { en: "go swimming", cn: "去游泳" },
    // Unit 3 月份 (12词)
    { en: "January", cn: "一月" },
    { en: "February", cn: "二月" },
    { en: "March", cn: "三月" },
    { en: "April", cn: "四月" },
    { en: "May", cn: "五月" },
    { en: "June", cn: "六月" },
    { en: "July", cn: "七月" },
    { en: "August", cn: "八月" },
    { en: "September", cn: "九月" },
    { en: "October", cn: "十月" },
    { en: "November", cn: "十一月" },
    { en: "December", cn: "十二月" },
    // Unit 4 序数词 (10词)
    { en: "first", cn: "第一" },
    { en: "second", cn: "第二" },
    { en: "third", cn: "第三" },
    { en: "fourth", cn: "第四" },
    { en: "fifth", cn: "第五" },
    { en: "twelfth", cn: "第十二" },
    { en: "twentieth", cn: "第二十" },
    { en: "twenty-first", cn: "第二十一" },
    { en: "twenty-third", cn: "第二十三" },
    { en: "thirtieth", cn: "第三十" },
    // Unit 5 正在进行 (12词)
    { en: "mine", cn: "我的" },
    { en: "yours", cn: "你的" },
    { en: "his", cn: "他的" },
    { en: "hers", cn: "她的" },
    { en: "theirs", cn: "他们的" },
    { en: "ours", cn: "我们的" },
    { en: "climbing", cn: "攀登" },
    { en: "eating", cn: "吃" },
    { en: "playing", cn: "玩耍" },
    { en: "jumping", cn: "跳" },
    { en: "drinking", cn: "喝" },
    { en: "sleeping", cn: "睡觉" },
    // Unit 6 规则 (12词)
    { en: "doing morning exercises", cn: "早锻炼" },
    { en: "having class", cn: "上课" },
    { en: "eating lunch", cn: "吃午饭" },
    { en: "reading a book", cn: "看书" },
    { en: "listening to music", cn: "听音乐" },
    { en: "keep", cn: "保持" },
    { en: "keep to the right", cn: "靠右" },
    { en: "keep your desk clean", cn: "保持课桌整洁" },
    { en: "talk quietly", cn: "小声讲话" },
    { en: "turn", cn: "顺序" },
    { en: "take turns", cn: "按顺序来" }
  ]
};

// 关卡配置
const LEVELS = [
  { id: 1, name: "魔法入门", words: "3a", range: [0, 17] },
  { id: 2, name: "颜色魔法", words: "3a", range: [18, 35] },
  { id: 3, name: "动物伙伴", words: "3a", range: [36, 57] },
  { id: 4, name: "数字咒语", words: "3a", range: [58, 67] },
  { id: 5, name: "新朋友", words: "3b", range: [0, 15] },
  { id: 6, name: "魔法家庭", words: "3b", range: [16, 28] },
  { id: 7, name: "变身魔法", words: "3b", range: [29, 40] },
  { id: 8, name: "魔法空间", words: "3b", range: [41, 52] },
  { id: 9, name: "水果盛宴", words: "3b", range: [53, 61] },
  { id: 10, name: "进阶数字", words: "3b", range: [62, 72] },
  { id: 11, name: "魔法教室", words: "4a", range: [0, 10] },
  { id: 12, name: "文具宝箱", words: "4a", range: [11, 19] },
  { id: 13, name: "变形术", words: "4a", range: [20, 31] },
  { id: 14, name: "魔法房间", words: "4a", range: [32, 41] },
  { id: 15, name: "美食魔法", words: "4a", range: [42, 52] },
  { id: 16, name: "职业魔法", words: "4a", range: [53, 70] },
  { id: 17, name: "魔法城堡", words: "4b", range: [0, 7] },
  { id: 18, name: "天气咒语", words: "4b", range: [8, 16] },
  { id: 19, name: "自然魔法", words: "4b", range: [17, 24] },
  { id: 20, name: "服装魔法", words: "4b", range: [25, 36] },
  { id: 21, name: "特性魔法", words: "5a", range: [0, 9] },
  { id: 22, name: "时间魔法", words: "5a", range: [10, 23] },
  { id: 23, name: "美味魔法", words: "5a", range: [24, 33] },
  { id: 24, name: "技能魔法", words: "5a", range: [34, 47] },
  { id: 25, name: "物品魔法", words: "5a", range: [48, 59] },
  { id: 26, name: "地点魔法", words: "5a", range: [60, 69] },
  { id: 27, name: "日常魔法", words: "5b", range: [0, 13] },
  { id: 28, name: "四季魔法", words: "5b", range: [14, 25] },
  { id: 29, name: "月份魔法", words: "5b", range: [26, 37] },
  { id: 30, name: "顺序魔法", words: "5b", range: [38, 47] },
  { id: 31, name: "物主魔法", words: "5b", range: [48, 59] },
  { id: 32, name: "规则魔法", words: "5b", range: [60, 71] }
];

// 获取关卡单词
function getLevelWords(levelId) {
  const level = LEVELS.find(l => l.id === levelId);
  if (!level) return [];
  
  const wordList = WORDS[level.words];
  if (!wordList) return [];
  
  return wordList.slice(level.range[0], level.range[1] + 1);
}

// 导出
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { WORDS, LEVELS, getLevelWords };
}
